apiVersion: apps/v1
kind: Deployment
metadata:
  name: learninghubmoodletest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learninghubmoodletest
  template:
    metadata:
      labels:
        app: learninghubmoodletest
    spec:
      containers:
      - name: learninghubmoodleimage
        image: learninghubmoodlecrdev.azurecr.io/learninghubmoodleimage:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: moodledata
          mountPath: /var/www/moodledata
          readOnly: false
      volumes:
      - name: moodledata
        persistentVolumeClaim:
          claimName: moodledataclaim