apiVersion: apps/v1
kind: Deployment
metadata:
  name: learninghubmoodleprod
spec:
  replicas: REPLICA-COUNT
  selector:
    matchLabels:
      app: learninghubmoodleprod
  template:
    metadata:
      labels:
        app: learninghubmoodleprod
    spec:
      containers:
      - name: learninghubmoodleimage
        image: learninghubmoodlecrprod.azurecr.io/learninghubmoodleimage:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: moodledata
          mountPath: /var/www/moodledata
          readOnly: false
      volumes:
      - name: moodledata
        persistentVolumeClaim:
          claimName: moodledataclaim