apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: themeclaim
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: azurefile-csi
  volumeName: theme