apiVersion: v1
kind: Service
metadata:
  name: learninghubmoodle-service
spec:
  selector:
    app: learninghubmoodledev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer